#!/usr/bin/env python3
"""
analysis/analyze.py — ingest results/*.csv, compute summary stats,
produce figures/ and tables/ for §7, and emit numbers.tex.

Usage: python analysis/analyze.py [--results-dir results] [--out-dir analysis]
"""

import argparse
import csv
import json
import os
import sys
from pathlib import Path

# ─── CLI ──────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--results-dir", default="results")
    p.add_argument("--out-dir", default="analysis")
    return p.parse_args()

# ─── Ingestion ────────────────────────────────────────────────────────────────

def load_run(path: Path) -> dict:
    """Load a single CSV result file into a flat dict."""
    data = {}
    with open(path) as f:
        reader = csv.reader(f)
        next(reader, None)  # skip header
        for row in reader:
            if len(row) >= 2:
                data[row[0]] = row[1]
    data["_file"] = path.stem
    return data

def load_all(results_dir: str) -> list[dict]:
    runs = []
    for p in sorted(Path(results_dir).glob("*.csv")):
        try:
            runs.append(load_run(p))
        except Exception as e:
            print(f"  warn: skipping {p}: {e}", file=sys.stderr)
    return runs

# ─── Summary statistics ───────────────────────────────────────────────────────

def summarize(runs: list[dict]) -> dict:
    """Compute per-workload summary statistics."""
    by_workload: dict[str, list] = {}
    for r in runs:
        wl = r.get("workload", "unknown")
        by_workload.setdefault(wl, []).append(r)

    summary = {}
    for wl, rs in by_workload.items():
        jains = [float(r["jain_index"]) for r in rs if "jain_index" in r]
        p50s  = [float(r["p50_latency_s"]) for r in rs if "p50_latency_s" in r]
        p99s  = [float(r["p99_latency_s"]) for r in rs if "p99_latency_s" in r]
        summary[wl] = {
            "n_runs": len(rs),
            "jain_mean": _mean(jains),
            "jain_min":  min(jains) if jains else None,
            "jain_max":  max(jains) if jains else None,
            "p50_mean":  _mean(p50s),
            "p99_mean":  _mean(p99s),
        }
    return summary

def _mean(xs):
    return sum(xs) / len(xs) if xs else None

# ─── Output helpers ───────────────────────────────────────────────────────────

def write_numbers_tex(summary: dict, out_dir: str):
    """Emit a numbers.tex file with one \newcommand per key result."""
    lines = [
        "% Auto-generated by analysis/analyze.py — DO NOT EDIT MANUALLY",
        "% Source of truth for §7 numbers. Include in paper with \\input{numbers.tex}.",
        "",
    ]

    def cmd(name, value, comment=""):
        if value is None:
            value = r"\textbf{TBD}"
        elif isinstance(value, float):
            value = f"{value:.3f}"
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}} % {comment}")

    for wl, s in summary.items():
        safe = wl.replace("-", "")
        cmd(f"jain{safe}Mean",  s["jain_mean"],  f"H1a Jain index mean ({wl})")
        cmd(f"jain{safe}Min",   s["jain_min"],   f"H1a Jain index min  ({wl})")
        cmd(f"p99{safe}Mean",   s["p99_mean"],   f"p99 latency (s) mean ({wl})")

    path = Path(out_dir) / "tables" / "numbers.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    print(f"Wrote {path}")

def write_summary_json(summary: dict, out_dir: str):
    path = Path(out_dir) / "tables" / "summary.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(summary, indent=2, default=str))
    print(f"Wrote {path}")

def write_table_csv(runs: list[dict], out_dir: str):
    """Write a flat table of all runs for inspection."""
    if not runs:
        return
    keys = ["_file", "workload", "n_agents", "seed", "jain_index",
            "p50_latency_s", "p99_latency_s", "starvation_events"]
    path = Path(out_dir) / "tables" / "all_runs.csv"
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys, extrasaction="ignore")
        w.writeheader()
        w.writerows(runs)
    print(f"Wrote {path}")

# ─── Figure stubs ─────────────────────────────────────────────────────────────

def try_make_figures(runs: list[dict], out_dir: str):
    """Attempt to produce matplotlib figures; skip gracefully if not installed."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        _make_jain_bar(runs, out_dir, plt)
    except ImportError:
        print("matplotlib not installed — skipping figures (pip install matplotlib)")

def _make_jain_bar(runs, out_dir, plt):
    by_wl: dict[str, list] = {}
    for r in runs:
        wl = r.get("workload", "?")
        if "jain_index" in r:
            by_wl.setdefault(wl, []).append(float(r["jain_index"]))

    if not by_wl:
        return

    labels = list(by_wl.keys())
    means = [_mean(by_wl[k]) or 0 for k in labels]

    fig, ax = plt.subplots(figsize=(8, 4))
    ax.bar(labels, means, color="steelblue", alpha=0.8)
    ax.axhline(0.9, color="red", linestyle="--", label="H1a target (0.9)")
    ax.set_xlabel("Workload")
    ax.set_ylabel("Jain Fairness Index")
    ax.set_title("H1a: Jain Index by Workload (RVT)")
    ax.legend()
    ax.set_ylim(0, 1.05)

    path = Path(out_dir) / "figures" / "h1a_jain.pdf"
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote {path}")

# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    args = parse_args()
    runs = load_all(args.results_dir)
    print(f"Loaded {len(runs)} result files from {args.results_dir}/")

    if not runs:
        print("No results yet — run experiments/run.sh first.")
        return

    summary = summarize(runs)
    write_summary_json(summary, args.out_dir)
    write_table_csv(runs, args.out_dir)
    write_numbers_tex(summary, args.out_dir)
    try_make_figures(runs, args.out_dir)

    print("\n=== Summary ===")
    for wl, s in summary.items():
        jain = s["jain_mean"]
        jain_str = f"{jain:.3f}" if jain is not None else "TBD"
        print(f"  {wl:15s}  Jain={jain_str}  n_runs={s['n_runs']}")

if __name__ == "__main__":
    main()
