#!/usr/bin/env python3
"""
analysis/analyze.py — ingest results/*.csv, compute summary stats,
produce figures/ and tables/ for §7, and emit numbers.tex.

Usage: python analysis/analyze.py [--results-dir results] [--out-dir analysis]
"""

import argparse
import csv
import json
import os
import sys
from pathlib import Path
from collections import defaultdict

# ─── CLI ──────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--results-dir", default="results")
    p.add_argument("--out-dir", default="analysis")
    return p.parse_args()

# ─── Ingestion ────────────────────────────────────────────────────────────────

def load_run(path: Path) -> dict:
    data = {}
    with open(path) as f:
        reader = csv.reader(f)
        next(reader, None)
        for row in reader:
            if len(row) >= 2:
                data[row[0]] = row[1]
    data["_file"] = path.stem
    return data

def load_all(results_dir: str):
    bench_runs, eval_runs = [], []
    for p in sorted(Path(results_dir).glob("*.csv")):
        try:
            r = load_run(p)
            if "overhead_ns_per_call" in r:
                bench_runs.append(r)
            else:
                eval_runs.append(r)
        except Exception as e:
            print(f"  warn: skipping {p}: {e}", file=sys.stderr)
    return bench_runs, eval_runs

def fv(r, key, default=None):
    try:
        return float(r[key])
    except (KeyError, ValueError, TypeError):
        return default

def iv(r, key, default=None):
    try:
        return int(r[key])
    except (KeyError, ValueError, TypeError):
        return default

def bv(r, key, default=False):
    return r.get(key, "").lower() == "true"

# ─── H0a bench numbers ────────────────────────────────────────────────────────

def extract_bench(bench_runs):
    by_n = {}
    for r in bench_runs:
        n = iv(r, "n_agents")
        by_n[n] = {
            "overhead_ns": fv(r, "overhead_ns_per_call"),
            "wall_pct":    fv(r, "wall_overhead_pct"),
            "token_pct":   fv(r, "token_overhead_pct"),
            "h0a_pass":    bv(r, "h0a_pass"),
        }
    return by_n

# ─── H1a / H1b evaluation numbers ─────────────────────────────────────────────

def extract_eval(eval_runs):
    """Returns structured dict keyed by (sched, workload, n_agents, seed)."""
    rows = []
    for r in eval_runs:
        rows.append({
            "sched":       r.get("sched", "rvt"),
            "workload":    r.get("workload", "unknown"),
            "n":           iv(r, "n_agents"),
            "seed":        iv(r, "seed"),
            "reconcile":   r.get("reconcile", "true") == "true",
            "jain":        fv(r, "jain_index"),
            "p50":         fv(r, "p50_latency_s"),
            "p99":         fv(r, "p99_latency_s"),
            "starvation":  iv(r, "starvation_events", 0),
            "gap_ratio":   fv(r, "max_gap_ratio"),
            "thm1":        bv(r, "thm1_satisfied"),
            "_file":       r.get("_file", ""),
        })
    return rows

def select(rows, **kw):
    """Filter rows by exact field matches."""
    out = []
    for r in rows:
        if all(r.get(k) == v for k, v in kw.items()):
            out.append(r)
    return out

def _mean(xs):
    xs = [x for x in xs if x is not None]
    return sum(xs) / len(xs) if xs else None

def _min(xs):
    xs = [x for x in xs if x is not None]
    return min(xs) if xs else None

def _max(xs):
    xs = [x for x in xs if x is not None]
    return max(xs) if xs else None

# ─── numbers.tex emission ─────────────────────────────────────────────────────

def write_numbers_tex(bench, rows, out_dir):
    lines = [
        "% Auto-generated by analysis/analyze.py — DO NOT EDIT MANUALLY",
        "% Source of truth for paper §7 numbers. Include with \\input{analysis/tables/numbers.tex}.",
        "",
        "% ── H0a: scheduling overhead ─────────────────────────────────────",
    ]

    def cmd(name, value, comment="", fmt=".4f"):
        if value is None:
            v = r"\textbf{[TBD]}"
        elif isinstance(value, bool):
            v = "true" if value else "false"
        elif isinstance(value, float):
            v = f"{value:{fmt}}"
        elif isinstance(value, int):
            v = str(value)
        else:
            v = str(value)
        lines.append(f"\\newcommand{{\\{name}}}{{{v}}} % {comment}")

    # H0a bench
    b10 = bench.get(10, {})
    b50 = bench.get(50, {})
    cmd("HZeroOverheadNsTen",  b10.get("overhead_ns"),  "H0a n=10 overhead ns/call", fmt=".0f")
    cmd("HZeroWallPctTen",     b10.get("wall_pct"),     "H0a n=10 wall overhead %",  fmt=".4f")
    cmd("HZeroTokenPctTen",    b10.get("token_pct"),    "H0a n=10 token overhead %", fmt=".2f")
    cmd("HZeroOverheadNsFifty",b50.get("overhead_ns"),  "H0a n=50 overhead ns/call", fmt=".0f")
    cmd("HZeroWallPctFifty",   b50.get("wall_pct"),     "H0a n=50 wall overhead %",  fmt=".4f")
    cmd("HZeroTokenPctFifty",  b50.get("token_pct"),    "H0a n=50 token overhead %", fmt=".2f")

    lines.append("")
    lines.append("% ── H1a: Jain fairness index (skewed workload) ──────────────────")

    # RVT skewed
    for n in [2, 10, 50]:
        rs = select(rows, sched="rvt", workload="skewed", n=n)
        jains = [r["jain"] for r in rs if r["jain"] is not None]
        label = {2: "Two", 10: "Ten", 50: "Fifty"}[n]
        cmd(f"RVTJainSkewed{label}", _mean(jains), f"H1a RVT skewed n={n} Jain mean", fmt=".4f")

    # FCFS & RR vs RVT at n=10
    for sched, name in [("fcfs", "FCFS"), ("rr", "RR")]:
        rs = select(rows, sched=sched, workload="skewed", n=10)
        jains = [r["jain"] for r in rs if r["jain"] is not None]
        cmd(f"{name}JainSkewedTen", _mean(jains), f"H1a {sched.upper()} skewed n=10 Jain", fmt=".4f")

    # Seed robustness (n=10, RVT, multiple seeds)
    seed_rows = [r for r in select(rows, sched="rvt", workload="skewed", n=10)
                 if r["_file"].startswith("rvt_skewed_n10_seed")]
    seed_jains = [r["jain"] for r in seed_rows if r["jain"] is not None]
    cmd("RVTJainSeedMin", _min(seed_jains), "H1a RVT seed-robustness Jain min", fmt=".4f")
    cmd("RVTJainSeedMax", _max(seed_jains), "H1a RVT seed-robustness Jain max", fmt=".4f")
    cmd("RVTJainSeedN",   len(seed_rows),   "H1a RVT seed-robustness # seeds")

    lines.append("")
    lines.append("% ── H1b: Theorem 1 gap/bound ratio ──────────────────────────────")

    # Theorem 1 (skewed, RVT, with reconciliation only)
    for n in [2, 10, 50]:
        rs = select(rows, sched="rvt", workload="skewed", n=n, reconcile=True)
        ratios = [r["gap_ratio"] for r in rs if r["gap_ratio"] is not None]
        label = {2: "Two", 10: "Ten", 50: "Fifty"}[n]
        cmd(f"RVTGapRatioSkewed{label}", _mean(ratios), f"H1b RVT gap/bound ratio n={n} (reconcile=true)", fmt=".4f")

    # Theorem 1 satisfied?
    rs10 = select(rows, sched="rvt", workload="skewed", n=10)
    thm1_all = all(r["thm1"] for r in rs10)
    cmd("RVTTheoremOneTen", "\\checkmark" if thm1_all else "\\xmark", "H1b Theorem 1 satisfied n=10")

    lines.append("")
    lines.append("% ── Proposition 2 ablation (no reconciliation) ──────────────────")

    # Prop 2 ablation
    recon_rows  = [r for r in rows if r["_file"] == "rvt_skewed_n10_c5000"]
    norecon_rows = [r for r in rows if r["_file"] == "rvt_skewed_n10_norecon"]
    if recon_rows:
        cmd("PropTwoGapWithRecon",    recon_rows[0]["gap_ratio"],   "Prop 2 gap ratio WITH reconcile", fmt=".4f")
    if norecon_rows:
        cmd("PropTwoGapWithoutRecon", norecon_rows[0]["gap_ratio"], "Prop 2 gap ratio WITHOUT reconcile", fmt=".4f")

    lines.append("")
    lines.append("% ── Additional workloads (RVT, n=10) ───────────────────────────")

    for wl in ["uniform", "adversarial", "heavytail", "mixed", "tworesource"]:
        rs = select(rows, sched="rvt", workload=wl, n=10)
        jains = [r["jain"] for r in rs if r["jain"] is not None]
        label = wl.capitalize()
        cmd(f"RVTJain{label}Ten", _mean(jains), f"RVT Jain {wl} n=10", fmt=".4f")

    path = Path(out_dir) / "tables" / "numbers.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {path}")

# ─── summary.json ─────────────────────────────────────────────────────────────

def write_summary_json(bench, rows, out_dir):
    # H1a summary table
    h1a = {}
    for sched in ["rvt", "fcfs", "rr"]:
        for n in [2, 10, 50]:
            rs = select(rows, sched=sched, workload="skewed", n=n)
            if rs:
                jains = [r["jain"] for r in rs if r["jain"] is not None]
                gaps  = [r["gap_ratio"] for r in rs if r["gap_ratio"] is not None]
                key = f"{sched}_n{n}"
                h1a[key] = {
                    "jain_mean":      _mean(jains),
                    "gap_ratio_mean": _mean(gaps),
                    "thm1_satisfied": all(r["thm1"] for r in rs),
                    "n_runs":         len(rs),
                }

    out = {
        "h0a": bench,
        "h1a_skewed": h1a,
        "seed_robustness": {
            "sched": "rvt", "workload": "skewed", "n": 10,
            "seeds": [r["seed"] for r in rows if r["_file"].startswith("rvt_skewed_n10_seed")],
            "jain_min": _min([r["jain"] for r in rows if r["_file"].startswith("rvt_skewed_n10_seed")]),
            "jain_max": _max([r["jain"] for r in rows if r["_file"].startswith("rvt_skewed_n10_seed")]),
        },
        "prop2_ablation": {
            "with_reconcile":    next((r["gap_ratio"] for r in rows if r["_file"] == "rvt_skewed_n10_c5000"), None),
            "without_reconcile": next((r["gap_ratio"] for r in rows if r["_file"] == "rvt_skewed_n10_norecon"), None),
        },
    }

    path = Path(out_dir) / "tables" / "summary.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(out, indent=2, default=str))
    print(f"Wrote {path}")

# ─── all_runs.csv ─────────────────────────────────────────────────────────────

def write_all_runs_csv(rows, out_dir):
    keys = ["_file", "sched", "workload", "n", "seed", "reconcile",
            "jain", "p50", "p99", "starvation", "gap_ratio", "thm1"]
    path = Path(out_dir) / "tables" / "all_runs.csv"
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)
    print(f"Wrote {path}")

# ─── Figures ──────────────────────────────────────────────────────────────────

def try_make_figures(bench, rows, out_dir):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        _fig_h1a_comparison(rows, out_dir, plt)
        _fig_h0a_table(bench, out_dir, plt)
        _fig_prop2_ablation(rows, out_dir, plt)
        _fig_workload_summary(rows, out_dir, plt)
    except ImportError:
        print("matplotlib not installed — skipping figures (pip install matplotlib)")

def _fig_h1a_comparison(rows, out_dir, plt):
    """Bar chart: RVT vs FCFS vs RR Jain at skewed n=10."""
    labels = ["RVT", "FCFS", "Round-Robin"]
    scheds = ["rvt", "fcfs", "rr"]
    colors = ["#2196F3", "#F44336", "#FF9800"]

    jains = []
    for s in scheds:
        rs = select(rows, sched=s, workload="skewed", n=10)
        jvals = [r["jain"] for r in rs if r["jain"] is not None]
        jains.append(_mean(jvals) or 0.0)

    fig, ax = plt.subplots(figsize=(6, 4))
    bars = ax.bar(labels, jains, color=colors, alpha=0.85, width=0.5)
    ax.axhline(0.9, color="black", linestyle="--", linewidth=1.2, label="H1a target (0.9)")
    for bar, val in zip(bars, jains):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                f"{val:.4f}", ha="center", va="bottom", fontsize=10, fontweight="bold")
    ax.set_ylabel("Jain Fairness Index", fontsize=12)
    ax.set_title("H1a: Fairness Under 32:1 Cost Skew (n=10 agents)", fontsize=11)
    ax.legend()
    ax.set_ylim(0, 1.15)

    path = Path(out_dir) / "figures" / "h1a_comparison.pdf"
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote {path}")

def _fig_h0a_table(bench, out_dir, plt):
    """Summary figure for H0a overhead."""
    ns   = sorted(bench.keys())
    ohns = [bench[n]["overhead_ns"] for n in ns]
    wpct = [bench[n]["wall_pct"] for n in ns]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(9, 4))

    ax1.bar([f"n={n}" for n in ns], ohns, color="#4CAF50", alpha=0.8)
    ax1.set_ylabel("Overhead (ns/call)")
    ax1.set_title("Scheduling Overhead per Call")
    for i, v in enumerate(ohns):
        ax1.text(i, v + 50, f"{v:.0f}ns", ha="center", fontsize=10)

    ax2.bar([f"n={n}" for n in ns], wpct, color="#9C27B0", alpha=0.8)
    ax2.axhline(5.0, color="red", linestyle="--", linewidth=1, label="H0a gate (5%)")
    ax2.set_ylabel("Wall Overhead (% of inference)")
    ax2.set_title("H0a: Wall Overhead vs Inference Time")
    ax2.legend()
    for i, v in enumerate(wpct):
        ax2.text(i, v + 0.0001, f"{v:.4f}%", ha="center", fontsize=10)

    fig.suptitle("H0a: RVT Scheduling Overhead (mean inference = 2s)", fontsize=12)
    fig.tight_layout()

    path = Path(out_dir) / "figures" / "h0a_overhead.pdf"
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote {path}")

def _fig_prop2_ablation(rows, out_dir, plt):
    """Bar chart: gap ratio with vs without reconciliation."""
    recon_r   = next((r for r in rows if r["_file"] == "rvt_skewed_n10_c5000"), None)
    norecon_r = next((r for r in rows if r["_file"] == "rvt_skewed_n10_norecon"), None)
    if not recon_r or not norecon_r:
        return

    labels = ["With Reconciliation\n(Proposition 2)", "Without Reconciliation"]
    vals   = [recon_r["gap_ratio"], norecon_r["gap_ratio"]]
    colors = ["#2196F3", "#F44336"]

    fig, ax = plt.subplots(figsize=(5, 4))
    bars = ax.bar(labels, vals, color=colors, alpha=0.85, width=0.4)
    ax.axhline(1.0, color="black", linestyle="--", linewidth=1.2, label="Theorem 1 bound (1.0x)")
    for bar, val in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                f"{val:.4f}x", ha="center", va="bottom", fontsize=10, fontweight="bold")
    ax.set_ylabel("Max Gap / Theorem 1 Bound")
    ax.set_title("Prop 2: Effect of Reconciliation on Gap Bound")
    ax.legend()
    ax.set_ylim(0, 1.2)

    path = Path(out_dir) / "figures" / "prop2_ablation.pdf"
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote {path}")

def _fig_workload_summary(rows, out_dir, plt):
    """H1a Jain for all workloads under RVT n=10."""
    wl_order = ["uniform", "skewed", "adversarial", "heavytail", "mixed", "tworesource"]
    wl_labels = ["Uniform", "Skewed\n(32:1)", "Adversarial", "Heavy\nTail", "Mixed\nPrio", "Two\nResource"]

    jains = []
    for wl in wl_order:
        rs = select(rows, sched="rvt", workload=wl, n=10)
        jvals = [r["jain"] for r in rs if r["jain"] is not None]
        jains.append(_mean(jvals))

    fig, ax = plt.subplots(figsize=(9, 4))
    colors = ["#2196F3" if j is not None and j >= 0.9 else "#FF9800"
              for j in jains]
    ax.bar(wl_labels, [j or 0 for j in jains], color=colors, alpha=0.85)
    ax.axhline(0.9, color="red", linestyle="--", linewidth=1.2, label="H1a target (0.9)")
    ax.set_ylabel("Jain Fairness Index")
    ax.set_title("§7.2: RVT Fairness Across All Workloads (n=10 agents)")
    ax.legend()
    ax.set_ylim(0, 1.1)
    for i, j in enumerate(jains):
        if j is not None:
            ax.text(i, j + 0.01, f"{j:.3f}", ha="center", va="bottom", fontsize=9)

    path = Path(out_dir) / "figures" / "workload_summary.pdf"
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote {path}")

# ─── Console summary ──────────────────────────────────────────────────────────

def print_summary(bench, rows):
    print("\n=== H0a: Scheduling Overhead ===")
    for n, b in sorted(bench.items()):
        gate = "PASS" if b["h0a_pass"] else "FAIL"
        print(f"  n={n:2d}  overhead={b['overhead_ns']:.0f}ns/call  "
              f"wall={b['wall_pct']:.4f}%  token={b['token_pct']:.2f}%  H0a:{gate}")

    print("\n=== H1a/H1b: Skewed Workload ===")
    print(f"  {'sched':6s}  {'n':3s}  {'Jain':8s}  {'GapRatio':9s}  {'Thm1':5s}")
    for sched in ["rvt", "fcfs", "rr"]:
        for n in [2, 10, 50]:
            rs = select(rows, sched=sched, workload="skewed", n=n, reconcile=True)
            if not rs:
                continue
            jain = _mean([r["jain"] for r in rs if r["jain"] is not None])
            gap  = _mean([r["gap_ratio"] for r in rs if r["gap_ratio"] is not None])
            thm  = "OK" if all(r["thm1"] for r in rs) else "--"
            jstr = f"{jain:.4f}" if jain is not None else "N/A"
            gstr = f"{gap:.4f}" if gap is not None else "N/A"
            print(f"  {sched:6s}  n={n:2d}  Jain={jstr}  gap={gstr}  thm1={thm}")

    print("\n=== Seed Robustness (RVT, skewed, n=10) ===")
    seed_rows = [r for r in rows if r["_file"].startswith("rvt_skewed_n10_seed")]
    if seed_rows:
        jains = [r["jain"] for r in seed_rows if r["jain"] is not None]
        print(f"  {len(seed_rows)} seeds: Jain in [{_min(jains):.4f}, {_max(jains):.4f}]  "
              f"all_thm1={all(r['thm1'] for r in seed_rows)}")

    print("\n=== Prop 2 Ablation ===")
    r_with    = next((r for r in rows if r["_file"] == "rvt_skewed_n10_c5000"), None)
    r_without = next((r for r in rows if r["_file"] == "rvt_skewed_n10_norecon"), None)
    if r_with:
        print(f"  With reconciliation:    gapRatio={r_with['gap_ratio']:.4f}x")
    if r_without:
        print(f"  Without reconciliation: gapRatio={r_without['gap_ratio']:.4f}x")

    print("\n=== Additional Workloads (RVT, n=10) ===")
    for wl in ["uniform", "adversarial", "heavytail", "mixed", "tworesource"]:
        rs = select(rows, sched="rvt", workload=wl, n=10)
        if rs:
            jain = _mean([r["jain"] for r in rs if r["jain"] is not None])
            print(f"  {wl:14s}  Jain={jain:.4f}" if jain is not None else f"  {wl:14s}  Jain=N/A")

# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    args = parse_args()
    bench_runs, eval_runs = load_all(args.results_dir)
    print(f"Loaded {len(bench_runs)} bench + {len(eval_runs)} eval result files from {args.results_dir}/")

    bench = extract_bench(bench_runs)
    rows  = extract_eval(eval_runs)

    Path(args.out_dir).mkdir(parents=True, exist_ok=True)

    write_numbers_tex(bench, rows, args.out_dir)
    write_summary_json(bench, rows, args.out_dir)
    write_all_runs_csv(rows, args.out_dir)
    try_make_figures(bench, rows, args.out_dir)
    print_summary(bench, rows)

if __name__ == "__main__":
    main()
